/* Generated By:JJTree: Do not edit this line. ASTOperation1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTOperation1 extends SimpleNode {
  public ASTOperation1(int id) {
    super(id);
  }

  public ASTOperation1(MyMiniParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyMiniParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a759ed90185cf2e8d27697c03561770b (do not edit this line) */
