/* Generated By:JJTree: Do not edit this line. ASTOperation3.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTOperation3 extends SimpleNode {
  public ASTOperation3(int id) {
    super(id);
  }

  public ASTOperation3(MyMiniParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyMiniParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=95b6d77dda227e98a2d64221a476b033 (do not edit this line) */
