/* Generated By:JJTree: Do not edit this line. ASTTerm1.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTTerm1 extends SimpleNode {
  public ASTTerm1(int id) {
    super(id);
  }

  public ASTTerm1(MyMiniParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyMiniParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=567aa1da398488f207d047dfa9c6345a (do not edit this line) */
